### ISSUE TITLE
Add sticky overlay to desktop layout

### ISSUE THREAD

**Issue by brigleb** [needmore/needmore-11-years#10] opened 2015-05-06 20:01 UTC
For layouts at the larger breakpoint, we should have a sticky overlay (perhaps click-to-close) that says basically what the page intro says. I think. Let's talk about that.

**Comment by sashaburchuk** [comment] 2015-05-07 18:37
So now we are going to go with sticky years at the top of each section. If we start with CSS (position:sticky) we'll need to use a polyfill to ensure cross-browser support. 

See these examples: 
http://www.getresponse.com/promo/15th-birthday
http://www.akita.co.uk/computing-history/#decade2000

**Comment by brigleb** [comment] 2015-05-08 16:51
I think this discussion is really more part of the behavior of the years at this point. This was kind of an overlay showing what the page was about. Just FYI.

**Comment by sashaburchuk** [comment] 2015-05-14 16:39
Closing this issue because it feels like a dupe of position:sticky which just got solved.

**Closed by sashaburchuk** 2015-05-14 16:39 UTC
Labels: enhancement
