### ISSUE TITLE
add dotted timeline

### ISSUE THREAD

**Issue by zebron** [needmore/needmore-11-years#27] opened 2015-05-13 19:57 UTC
On desktop having a dotted line going through the center of the page but not on mobile.

**Comment by zebron** [comment] 2015-05-14 17:31
Tried using CSS to create a vertical dotted line but I couldn't control the spacing. 

Instead I went with a repeating background image in a div. With some help from Gregor and Sasha We were able to get it to show up on the page using `position: absolute;`. However, it now sits on top of everything. We tried messing with the z-index and couldn't get it to work.

**Comment by brigleb** [comment] 2015-05-14 18:22
The way it was looking earlier was spot on, it just needs the dots to be closer together and maybe less than 100% opaque... Thanks!

**Comment by sashaburchuk** [comment] 2015-05-19 20:43
This is a duplicate of another issue. I'm closing this one because the branch is named after the other issue: https://github.com/needmore/needmore-11-years/tree/features/34-add-dotted-timeline

**Closed by sashaburchuk** 2015-05-19 20:43 UTC
